#!/usr/bin/env python3
"""Generate Zig Unicode interval tables used by zig-textcell.

Input is the Unicode Character Database layout used by uucode/zg clones. By
default this script reads ./tmp/upstream/uucode/ucd, which keeps development
repeatable after running the repository handoff's shallow-clone step.
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_UCD = ROOT / "tmp" / "upstream" / "uucode" / "ucd"
OUT = ROOT / "src" / "unicode_data.zig"

GCB_NAMES = {
    "CR": "cr",
    "LF": "lf",
    "Control": "control",
    "Extend": "extend",
    "ZWJ": "zwj",
    "Regional_Indicator": "regional_indicator",
    "Prepend": "prepend",
    "SpacingMark": "spacing_mark",
    "L": "l",
    "V": "v",
    "T": "t",
    "LV": "lv",
    "LVT": "lvt",
}


def parse_codepoint_range(field: str) -> tuple[int, int]:
    field = field.strip()
    if ".." in field:
        a, b = field.split("..", 1)
        return int(a, 16), int(b, 16)
    cp = int(field, 16)
    return cp, cp


def parse_property_file(path: Path, wanted: set[str] | None = None) -> dict[str, list[tuple[int, int]]]:
    props: dict[str, list[tuple[int, int]]] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or ";" not in line:
            continue
        lhs, rhs = [part.strip() for part in line.split(";", 1)]
        prop = rhs.split()[0]
        if wanted is not None and prop not in wanted:
            continue
        props.setdefault(prop, []).append(parse_codepoint_range(lhs))
    return props


def parse_incb(path: Path) -> dict[str, list[tuple[int, int]]]:
    props: dict[str, list[tuple[int, int]]] = {"Consonant": [], "Extend": [], "Linker": []}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [part.strip() for part in line.split(";")]
        if len(parts) < 3 or parts[1] != "InCB":
            continue
        value = parts[2].split()[0]
        if value in props:
            props[value].append(parse_codepoint_range(parts[0]))
    return props


def merge_ranges(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    if not ranges:
        return []
    ranges = sorted(ranges)
    merged = [ranges[0]]
    for lo, hi in ranges[1:]:
        last_lo, last_hi = merged[-1]
        if lo <= last_hi + 1:
            merged[-1] = (last_lo, max(last_hi, hi))
        else:
            merged.append((lo, hi))
    return merged


def fmt_ranges(ranges: list[tuple[int, int]], indent: str = "    ") -> str:
    return "\n".join(f"{indent}.{{ .lo = 0x{lo:X}, .hi = 0x{hi:X} }}," for lo, hi in ranges)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ucd", type=Path, default=DEFAULT_UCD)
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()

    ucd = args.ucd
    gcb = parse_property_file(ucd / "auxiliary" / "GraphemeBreakProperty.txt", set(GCB_NAMES))
    eaw = parse_property_file(ucd / "extracted" / "DerivedEastAsianWidth.txt", {"W", "F"})
    emoji = parse_property_file(
        ucd / "emoji" / "emoji-data.txt",
        {"Emoji_Presentation", "Extended_Pictographic", "Emoji_Modifier"},
    )
    incb = parse_incb(ucd / "DerivedCoreProperties.txt")

    gcb_entries: list[tuple[int, int, str]] = []
    for prop, zig_name in GCB_NAMES.items():
        for lo, hi in gcb.get(prop, []):
            gcb_entries.append((lo, hi, zig_name))
    gcb_entries.sort()

    wide = merge_ranges(eaw.get("W", []) + eaw.get("F", []))
    emoji_presentation = merge_ranges(emoji.get("Emoji_Presentation", []))
    extended_pictographic = merge_ranges(emoji.get("Extended_Pictographic", []))
    emoji_modifier = merge_ranges(emoji.get("Emoji_Modifier", []))

    incb_entries: list[tuple[int, int, str]] = []
    for prop, zig_name in {
        "Consonant": "consonant",
        "Extend": "extend",
        "Linker": "linker",
    }.items():
        for lo, hi in incb.get(prop, []):
            incb_entries.append((lo, hi, zig_name))
    incb_entries.sort()

    content = f"""// Generated by tools/update_unicode_data.py from Unicode 17.0.0 data.\n//\n// Unicode data files are © Unicode, Inc. and used under the Unicode License.\n// See: https://www.unicode.org/license.txt\n\npub const GraphemeBreakProperty = enum {{\n    other,\n    cr,\n    lf,\n    control,\n    extend,\n    zwj,\n    regional_indicator,\n    prepend,\n    spacing_mark,\n    l,\n    v,\n    t,\n    lv,\n    lvt,\n}};\n\npub const IndicConjunctBreak = enum {{\n    none,\n    consonant,\n    extend,\n    linker,\n}};\n\npub const Range = struct {{\n    lo: u21,\n    hi: u21,\n}};\n\npub const GraphemeBreakRange = struct {{\n    lo: u21,\n    hi: u21,\n    prop: GraphemeBreakProperty,\n}};\n\npub const IndicConjunctBreakRange = struct {{\n    lo: u21,\n    hi: u21,\n    prop: IndicConjunctBreak,\n}};\n\npub const grapheme_break_ranges = [_]GraphemeBreakRange{{\n"""
    content += "\n".join(
        f"    .{{ .lo = 0x{lo:X}, .hi = 0x{hi:X}, .prop = .{prop} }}," for lo, hi, prop in gcb_entries
    )
    content += f"""\n}};\n\npub const indic_conjunct_break_ranges = [_]IndicConjunctBreakRange{{\n"""
    content += "\n".join(
        f"    .{{ .lo = 0x{lo:X}, .hi = 0x{hi:X}, .prop = .{prop} }}," for lo, hi, prop in incb_entries
    )
    content += f"""\n}};\n\npub const wide_ranges = [_]Range{{\n{fmt_ranges(wide)}\n}};\n\npub const emoji_presentation_ranges = [_]Range{{\n{fmt_ranges(emoji_presentation)}\n}};\n\npub const extended_pictographic_ranges = [_]Range{{\n{fmt_ranges(extended_pictographic)}\n}};\n\npub const emoji_modifier_ranges = [_]Range{{\n{fmt_ranges(emoji_modifier)}\n}};\n"""

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(f"wrote {args.out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
